//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalPack.Efectivo.SSP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CLP")]
        public string moneda {
            get {
                return ((string)(this["moneda"]));
            }
            set {
                this["moneda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int milCLP {
            get {
                return ((int)(this["milCLP"]));
            }
            set {
                this["milCLP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int dosMilCLP {
            get {
                return ((int)(this["dosMilCLP"]));
            }
            set {
                this["dosMilCLP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int cincoMilCLP {
            get {
                return ((int)(this["cincoMilCLP"]));
            }
            set {
                this["cincoMilCLP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int diezMilCLP {
            get {
                return ((int)(this["diezMilCLP"]));
            }
            set {
                this["diezMilCLP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int veinteMilCLP {
            get {
                return ((int)(this["veinteMilCLP"]));
            }
            set {
                this["veinteMilCLP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool men_puerta {
            get {
                return ((bool)(this["men_puerta"]));
            }
            set {
                this["men_puerta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool men_corriente {
            get {
                return ((bool)(this["men_corriente"]));
            }
            set {
                this["men_corriente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool men_minBillete {
            get {
                return ((bool)(this["men_minBillete"]));
            }
            set {
                this["men_minBillete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool men_maxBillete {
            get {
                return ((bool)(this["men_maxBillete"]));
            }
            set {
                this["men_maxBillete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool men_minMonedas {
            get {
                return ((bool)(this["men_minMonedas"]));
            }
            set {
                this["men_minMonedas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool men_maxMonedas {
            get {
                return ((bool)(this["men_maxMonedas"]));
            }
            set {
                this["men_maxMonedas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool men_disDiferente {
            get {
                return ((bool)(this["men_disDiferente"]));
            }
            set {
                this["men_disDiferente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool men_atascoSeguro {
            get {
                return ((bool)(this["men_atascoSeguro"]));
            }
            set {
                this["men_atascoSeguro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool men_atascoInSeguro {
            get {
                return ((bool)(this["men_atascoInSeguro"]));
            }
            set {
                this["men_atascoInSeguro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool men_intentoFraudeB {
            get {
                return ((bool)(this["men_intentoFraudeB"]));
            }
            set {
                this["men_intentoFraudeB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool men_cajaFull {
            get {
                return ((bool)(this["men_cajaFull"]));
            }
            set {
                this["men_cajaFull"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool men_unidadAtascada {
            get {
                return ((bool)(this["men_unidadAtascada"]));
            }
            set {
                this["men_unidadAtascada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool men_monedaAtascada {
            get {
                return ((bool)(this["men_monedaAtascada"]));
            }
            set {
                this["men_monedaAtascada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool men_busquedaFallida {
            get {
                return ((bool)(this["men_busquedaFallida"]));
            }
            set {
                this["men_busquedaFallida"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool men_intentoFraudeM {
            get {
                return ((bool)(this["men_intentoFraudeM"]));
            }
            set {
                this["men_intentoFraudeM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool men_flotacion {
            get {
                return ((bool)(this["men_flotacion"]));
            }
            set {
                this["men_flotacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bloEf_corriente {
            get {
                return ((bool)(this["bloEf_corriente"]));
            }
            set {
                this["bloEf_corriente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bloEf_puerta {
            get {
                return ((bool)(this["bloEf_puerta"]));
            }
            set {
                this["bloEf_puerta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bloEf_maxBillete {
            get {
                return ((bool)(this["bloEf_maxBillete"]));
            }
            set {
                this["bloEf_maxBillete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bloEf_maxMonedas {
            get {
                return ((bool)(this["bloEf_maxMonedas"]));
            }
            set {
                this["bloEf_maxMonedas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bloEf_disDiferente {
            get {
                return ((bool)(this["bloEf_disDiferente"]));
            }
            set {
                this["bloEf_disDiferente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bloEf_atascoSeguro {
            get {
                return ((bool)(this["bloEf_atascoSeguro"]));
            }
            set {
                this["bloEf_atascoSeguro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bloEf_atascoInSeguro {
            get {
                return ((bool)(this["bloEf_atascoInSeguro"]));
            }
            set {
                this["bloEf_atascoInSeguro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bloEf_intentoFraudeB {
            get {
                return ((bool)(this["bloEf_intentoFraudeB"]));
            }
            set {
                this["bloEf_intentoFraudeB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bloEf_cajaFull {
            get {
                return ((bool)(this["bloEf_cajaFull"]));
            }
            set {
                this["bloEf_cajaFull"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bloEf_unidadAtascada {
            get {
                return ((bool)(this["bloEf_unidadAtascada"]));
            }
            set {
                this["bloEf_unidadAtascada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bloEf_monedaAtascada {
            get {
                return ((bool)(this["bloEf_monedaAtascada"]));
            }
            set {
                this["bloEf_monedaAtascada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bloEf_busquedaFallida {
            get {
                return ((bool)(this["bloEf_busquedaFallida"]));
            }
            set {
                this["bloEf_busquedaFallida"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bloEf_intentoFraudeM {
            get {
                return ((bool)(this["bloEf_intentoFraudeM"]));
            }
            set {
                this["bloEf_intentoFraudeM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bloEf_flotacion {
            get {
                return ((bool)(this["bloEf_flotacion"]));
            }
            set {
                this["bloEf_flotacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int diezPesosCLP {
            get {
                return ((int)(this["diezPesosCLP"]));
            }
            set {
                this["diezPesosCLP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int cincuentaPesosCLP {
            get {
                return ((int)(this["cincuentaPesosCLP"]));
            }
            set {
                this["cincuentaPesosCLP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("570")]
        public int cienPesosCLP {
            get {
                return ((int)(this["cienPesosCLP"]));
            }
            set {
                this["cienPesosCLP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int quinientosPesosCLP {
            get {
                return ((int)(this["quinientosPesosCLP"]));
            }
            set {
                this["quinientosPesosCLP"] = value;
            }
        }
    }
}
